import { Property, Plot } from './types';

export const properties: Property[] = [
  {
    id: 'prop-001',
    name: 'The Golden Fields',
    location: 'Kokapet, Hyderabad',
    description: 'A premium residential plot development in Kokapet, showcasing lush green lawns and pristine architectural boundaries. Perfectly configured at dusk with glowing ambient streetlights reflecting on high-quality gravel paths.',
    tag: 'Premium Plot',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1444653389962-8149286c578a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545466835-752157521fa9?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '14.5 Acres',
    totalPlots: 32,
    landType: 'Residential',
    zoning: 'R-1 Residential',
    status: 'Open for Sale',
    priceRange: '₹12.5 Cr - ₹18 Cr',
    avgPlotArea: '2,400 sq.ft',
    isCustomBuildAvailable: true,
  },
  {
    id: 'prop-002',
    name: 'Emerald Estates',
    location: 'Mokila, Hyderabad',
    description: 'A luxury plot development featuring wide, clean-cut rectangular plots of vibrant green grass separated by elegant stone-paved walkways. Designed as a high-end gated community with modern layout precision.',
    tag: 'Investment Grade',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '22.0 Acres',
    totalPlots: 48,
    landType: 'Residential',
    zoning: 'Gated Villa Plot',
    status: 'Selling Fast',
    priceRange: '₹8.5 Cr - ₹15 Cr',
    avgPlotArea: '3,500 sq.ft',
    isCustomBuildAvailable: true,
  },
  {
    id: 'prop-003',
    name: 'Horizon Heights',
    location: 'Tellapur, Hyderabad',
    description: 'An elevated plot location overlooking a serene valley. High-end leveling already done; perfect for constructing your dream modern 3-story luxury villa with walking trails and sweeping high-altitude views.',
    tag: 'Limited Release',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '18.2 Acres',
    totalPlots: 25,
    landType: 'Residential',
    zoning: 'Luxury Gated Commune',
    status: 'Exclusive Release',
    priceRange: '₹15 Cr - ₹24 Cr',
    avgPlotArea: '4,800 sq.ft',
    isCustomBuildAvailable: true,
  },
  {
    id: 'prop-004',
    name: 'Emerald Heights Phase I',
    location: 'Dubai Hills, Dubai',
    description: 'A high-end master-planned project overlooking clean horizons with pristine, build-ready soil configurations. Perfectly curated for global investors demanding precision zoning and compliance.',
    tag: 'Premium Sector',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '12.4 Acres',
    totalPlots: 15,
    landType: 'Residential Plot',
    zoning: 'Villas & Mansions',
    status: 'Open for Registration',
    priceRange: 'AED 12.5M - AED 18M',
    avgPlotArea: '12,450 sq ft',
    isCustomBuildAvailable: false,
  },
  {
    id: 'prop-005',
    name: 'Sapphire Cove Residences',
    location: 'Palm Jumeirah, Dubai',
    description: 'Bespoke shoreline layout with private beaches and clear blue horizons. Offers dynamic potential for absolute architectural personalization inside the iconic crescent sector.',
    tag: 'Waterfront',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '8.0 Acres',
    totalPlots: 8,
    landType: 'Waterfront Sand Plot',
    zoning: 'Signature Villa Only',
    status: 'Highly Secured',
    priceRange: 'AED 45M - AED 62M',
    avgPlotArea: '24,000 sq ft',
    isCustomBuildAvailable: false,
  },
  {
    id: 'prop-006',
    name: 'The Al-Barari Groves',
    location: 'Al Barari, Dubai',
    description: 'An expansive high-density woodland oasis offering peak landscape integration and raw organic potential within a highly curated modern perimeter.',
    tag: 'Heritage Site',
    image: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=1200&q=80',
    ],
    totalArea: '25.0 Acres',
    totalPlots: 20,
    landType: 'Forestland Residential',
    zoning: 'Eco-Luxury Estates',
    status: 'Reserved Release',
    priceRange: 'AED 18M - AED 24M',
    avgPlotArea: '18,200 sq ft',
    isCustomBuildAvailable: false,
  }
];

export const plotsData: Record<string, Plot[]> = {
  'prop-001': [
    {
      id: 'Plot #042',
      dimensions: '40ft x 60ft',
      area: '2,400 sq.ft',
      price: 125000000, // INR
      status: 'AVAILABLE',
      setbacks: 'F: 15ft | S: 10ft',
      maxFar: '2.5 Residential',
      notes: 'This corner plot offers dual-access potential and premium elevation overlooking the eastern valley. Ideal for a contemporary 3-story luxury villa with a walk-out basement.',
      width: 40,
      height: 60,
    },
    {
      id: 'Plot #043',
      dimensions: '50ft x 70ft',
      area: '3,500 sq.ft',
      price: 185000000,
      status: 'RESERVED',
      setbacks: 'F: 15ft | S: 12ft',
      maxFar: '2.5 Residential',
      notes: 'A focused deep rectangle plot showcasing visual maturity. Centered right along the high-prestige private boulevard.',
      width: 50,
      height: 70,
    },
    {
      id: 'Plot #044',
      dimensions: '60ft x 80ft',
      area: '4,800 sq.ft',
      price: 245000000,
      status: 'AVAILABLE',
      setbacks: 'F: 18ft | S: 15ft',
      maxFar: '2.8 Premium Gated',
      notes: 'Premium oversized plot with extensive dual road frontage. Features direct access to the sector clubhouse and central green spine of Kokapet.',
      width: 60,
      height: 80,
    },
    {
      id: 'Plot #045',
      dimensions: '45ft x 65ft',
      area: '2,925 sq.ft',
      price: 158000000,
      status: 'AVAILABLE',
      setbacks: 'F: 15ft | S: 10ft',
      maxFar: '2.5 Residential',
      notes: 'A spectacular sunset position looking over the lush valleys of Kokapet. Elevated topography ensures perpetual privacy and airflow.',
      width: 45,
      height: 65,
    }
  ],
  'prop-002': [
    {
      id: 'Plot #101',
      dimensions: '50ft x 70ft',
      area: '3,500 sq.ft',
      price: 85000000,
      status: 'AVAILABLE',
      setbacks: 'F: 15ft | S: 10ft',
      maxFar: '2.5 Residential Corridor',
      notes: 'Beautiful interior plot with direct view of the fountain plaza. Perfect rectangular orientation with Vastu-compliant layout.',
      width: 50,
      height: 70,
    },
    {
      id: 'Plot #102',
      dimensions: '60ft x 80ft',
      area: '4,800 sq.ft',
      price: 120000000,
      status: 'AVAILABLE',
      setbacks: 'F: 18ft | S: 12ft',
      maxFar: '2.8 Premium Gated',
      notes: 'Premium grand layout. Features high-security boundary wall interface and integrated utilities ready to connect.',
      width: 60,
      height: 80,
    },
    {
      id: 'Plot #103',
      dimensions: '70ft x 90ft',
      area: '6,300 sq.ft',
      price: 150000000,
      status: 'RESERVED',
      setbacks: 'F: 20ft | S: 15ft',
      maxFar: '3.0 Gated Estate',
      notes: 'Elite corner estate layout. Double-entry design possible with generous space for massive landscaped lawns and private swimming pool installations.',
      width: 70,
      height: 90,
    }
  ],
  'prop-003': [
    {
      id: 'Plot #201',
      dimensions: '60ft x 80ft',
      area: '4,800 sq.ft',
      price: 150000000,
      status: 'AVAILABLE',
      setbacks: 'F: 18ft | S: 12ft',
      maxFar: '2.8 Residential High-End',
      notes: 'Hilltop corner property with sunset views. The soil mechanics are already certified and optimized for zero-footprint foundations.',
      width: 60,
      height: 80,
    },
    {
      id: 'Plot #202',
      dimensions: '70ft x 100ft',
      area: '7,000 sq.ft',
      price: 240000000,
      status: 'AVAILABLE',
      setbacks: 'F: 20ft | S: 15ft',
      maxFar: '3.0 Grand Gated',
      notes: 'Our largest signature residential commune offering overlooking the private lake stream. Unobstructed view of the distant hills of Tellapur.',
      width: 70,
      height: 100,
    }
  ]
};

export const defaultPlots: Plot[] = [
  {
    id: 'Plot #042',
    dimensions: '40ft x 60ft',
    area: '2,400 sq.ft',
    price: 125000000,
    status: 'AVAILABLE',
    setbacks: 'F: 15ft | S: 10ft',
    maxFar: '2.5 Residential',
    notes: 'This corner plot offers dual-access potential and premium elevation overlooking the eastern valley. Ideal for a contemporary 3-story luxury villa with a walk-out basement.',
    width: 40,
    height: 60,
  },
  {
    id: 'Plot #043',
    dimensions: '50ft x 70ft',
    area: '3,500 sq.ft',
    price: 185000000,
    status: 'RESERVED',
    setbacks: 'F: 15ft | S: 12ft',
    maxFar: '2.5 Residential',
    notes: 'A focused deep rectangle plot showcasing visual maturity. Centered right along the high-prestige private boulevard.',
    width: 50,
    height: 70,
  },
  {
    id: 'Plot #044',
    dimensions: '60ft x 80ft',
    area: '4,800 sq.ft',
    price: 245000000,
    status: 'AVAILABLE',
    setbacks: 'F: 18ft | S: 15ft',
    maxFar: '2.8 Premium Gated',
    notes: 'Premium oversized plot with extensive dual road frontage. Features direct access to the central green spine.',
    width: 60,
    height: 80,
  },
  {
    id: 'Plot #045',
    dimensions: '45ft x 65ft',
    area: '2,925 sq.ft',
    price: 158000000,
    status: 'AVAILABLE',
    setbacks: 'F: 15ft | S: 10ft',
    maxFar: '2.5 Residential',
    notes: 'A spectacular sunset position looking over the lush valleys of Kokapet.',
    width: 45,
    height: 65,
  }
];
